apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: demo-jan
  description: Demo Domain for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: demo-team

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app-jan-janms-1
  description: Demo Application's Microservice-1
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=demo-app-jan-janms-1'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  providesApis:
   - harbor-api
  lifecycle: alpha
  owner: demo-team
  system: demo-app-jan

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app-jan-janms-2
  description: Demo Application's Microservice-2
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=demo-app-jan-janms-2'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  consumesApis:
   - harbor-api
  lifecycle: alpha
  owner: demo-team
  system: demo-app-jan

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo-app-jan
  description: Demo Application for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: demo-team
  domain: demo-jan

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: harbor-api
  description: The demo API for Tanzu Application Platform GUI
  links:
    - url: https://harbor.dieunkrauts.de/devcenter-api-2.0
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: demo-team
  system: demo-app-jan # Or specify system name of your choice
  definition: |
    openapi: 3.0.1
    info:
      title: Demo API
      description: defaultDescription
      version: '0.1'
    servers:
      - url: https://harbor.dieunkrauts.de/devcenter-api-2.0
    paths:
      - /:
          get:
            description: Auto generated using Swagger Inspector
            parameters:
              - name: name
                in: query
                schema:
                  type: string
                example: type_any_name
            responses:
              '200':
                description: Auto generated using Swagger Inspector
                content:
                  application/json; charset=utf-8:
                    schema:
                      type: string
                    examples: {}
      - /project:
          get:
            description: test harbor get project
            parameters:
              - name: name
                in: query
                schema:
                  type: string
                example: type_any_name
